### PR TITLE
Support for extra status lights ( preview and error )

### PR DESCRIPTION
**Pull request by kristofkeppens**

### CODE REVIEW

**Comment by ppettit** [comment]
Thanks! this looks cool!

Is there any chance you can make the default colours for the new statuses `#000000`? that way the behaviour won't change unexpectedly when upgrading.

**Comment by kristofkeppens** [comment]
@ppettit sure, I've changed the default and updated the readme.

**Comment by kristofkeppens** [comment]
I've found a remaining issue, the blinkstick color isn't reset when exiting galicaster, I'll look into that first and reopen the pull request when fixed.

**Comment by ppettit** [comment]
thanks!

**Pull request closed without merging**
